# Travis CI configuration file.

os:
  - linux

# Use the new Debian 14 containers.
dist: trusty
sudo: false

language: node_js
node_js:
  - "node"

git:
  # Limit the clone depth; default is 50.
  depth: 3

env:
  global:
    - SCRIPT="scripts/travis.sh"

before_install:
  - bash "${SCRIPT}" before_install

# Skip the install step.
# install: true

before_script:
  - bash "${SCRIPT}" before_script

script:
  - bash "${SCRIPT}" script

# Unused, kept for just in case.

# after_success:
#  - bash "${SCRIPT}" after_success

# after_failure:
#   - bash "${SCRIPT}" after_failure
  
# after_script:
#   - bash "${SCRIPT}" after_script
